[template]
src = "default.conf.tmpl"
dest = "/home/app/default.conf"
owner = "app"
mode = "0644"
keys = [
  "/accessControlWhitelist",
  "/corsAllowOrigin",
  "/factomdNodes",
  "/healthCheck/clockSpreadToleranceInSeconds",
  "/healthCheck/maxBlockAgeInSeconds",
  "/listenPort",
  "/nginx/clientBodyBufferSize",
  "/nginx/keepAliveRequests",
  "/nginx/keepAliveTimeout",
  "/nginx/proxyBuffering",
  "/nginx/proxyConnectTimeout",
  "/nginx/proxyProtocol",
  "/nginx/proxyRequestBuffering",
  "/ssl/bufferSize",
  "/ssl/certificate",
  "/ssl/certificateKey",
  "/ssl/ciphers",
  "/ssl/dhParam",
  "/ssl/protocols",
  "/ssl/sessionCacheSize",
  "/ssl/sessionTimeout",
  "/ssl/trustedCertificate",
]
