[template]
src = "default.conf.tmpl"
dest = "/home/app/default.conf"
owner = "app"
mode = "0644"
keys = [
  "/corsAllowOrigin",
  "/factomdUrl",
  "/listenPort",
  "/sslCertificate",
  "/sslPrivateKey",
]
check_cmd = "/usr/bin/openresty -t"
reload_cmd = "/usr/bin/openresty -s reload"
