[template]
src = "default.conf.tmpl"
dest = "/home/nginx/default.conf"
owner = "nginx"
mode = "0644"
keys = [
  "/apiUrl",
  "/port",
]
check_cmd = "/usr/local/openresty/bin/openresty -t"
restart_cmd = "/usr/local/openresty -s reload"
