[template]
src = "dispatcher.lua.tmpl"
dest = "/home/nginx/modules/dispatcher.lua"
owner = "nginx"
mode = "0644"
keys = [
  "/allowOrigin",
]
check_cmd = "/usr/local/openresty/bin/openresty -t"
restart_cmd = "/usr/local/openresty -s reload"
