[template]
src = "ssl_dh_param.pem.tmpl"
dest = "/home/app/ssl/dhparam.pem"
owner = "app"
mode = "0644"
keys = [
  "/sslDhParam",
]
check_cmd = "/usr/bin/openresty -t"
reload_cmd = "/usr/bin/openresty -s reload"
