[template]
src = "ssl_certificate_key.pem.tmpl"
dest = "/home/app/ssl/certificate_key.pem"
owner = "app"
mode = "0644"
keys = [
  "/ssl/certificateKey",
]
check_cmd = "/usr/bin/openresty -t"
reload_cmd = "/usr/bin/openresty -s reload"
