[template]
src = "ssl_private_key.pem.tmpl"
dest = "/home/app/ssl/private_key.pem"
owner = "app"
mode = "0644"
keys = [
  "/sslPrivateKey",
]
check_cmd = "/usr/bin/openresty -t"
reload_cmd = "/usr/bin/openresty -s reload"
