[template]
src = "ssl_certificate.pem.tmpl"
dest = "/home/app/ssl/certificate.pem"
owner = "app"
mode = "0644"
keys = [
  "/sslCertificate",
]
check_cmd = "/usr/bin/openresty -t"
reload_cmd = "/usr/bin/openresty -s reload"
