[template]
src = "config_dump.tmpl"
dest = "/home/app/config_dump"
owner = "app"
mode = "0644"
keys = [
  "/accessControlWhitelist",
  "/corsAllowOrigin",
  "/factomdUrl",
  "/healthCheck/clockSpreadToleranceInSeconds",
  "/healthCheck/maxBlockAgeInSeconds",
  "/listenPort",
  "/nginx/clientBodyBufferSize",
  "/nginx/keepAliveRequests",
  "/nginx/keepAliveTimeout",
  "/ssl/bufferSize",
  "/ssl/certificate",
  "/ssl/certificateKey",
  "/ssl/ciphers",
  "/ssl/dhParam",
  "/ssl/protocols",
  "/ssl/sessionCacheSize",
  "/ssl/sessionTimeout",
  "/ssl/trustedCertificate",
]
check_cmd = "/usr/bin/openresty -t"
reload_cmd = "/usr/bin/openresty -s reload"
