[template]
src = "z_nginx_reload_helper.tmpl"
dest = "/home/app/nginx_reload_helper.raw"
owner = "app"
mode = "0644"
keys = [
  "/accessControlWhitelist",
  "/corsAllowOrigin",
  "/factomdUrl",
  "/healthCheck/clockSpreadToleranceInSeconds",
  "/healthCheck/maxBlockAgeInSeconds",
  "/listenPort",
  "/name",
  "/nginx/clientBodyBufferSize",
  "/nginx/keepAliveRequests",
  "/nginx/keepAliveTimeout",
  "/nginx/responseBuffering",
  "/nginx/proxyConnectTimeout",
  "/nginx/requestBuffering",
  "/rateLimiting/blockDurationInSeconds",
  "/rateLimiting/maxBurstWritesPerSecond",
  "/rateLimiting/maxWritesPerBlock",
  "/rateLimiting/maxWritesPerSecond",
  "/rateLimiting/writeMethods",
  "/ssl/bufferSize",
  "/ssl/certificate",
  "/ssl/certificateKey",
  "/ssl/ciphers",
  "/ssl/dhParam",
  "/ssl/protocols",
  "/ssl/sessionCacheSize",
  "/ssl/sessionTimeout",
  "/ssl/trustedCertificate",
  "/version",
]
check_cmd = "/usr/bin/openresty -t"
reload_cmd = "/usr/bin/openresty -s reload"
