[template]
src = "z_nginx_reload_helper.tmpl"
dest = "/home/app/nginx_reload_helper.raw"
owner = "app"
mode = "0644"
keys = [
  "/accessControlWhitelist",
  "/corsAllowOrigin",
  "/factomdPool",
  "/healthCheck/clockSpreadToleranceInSeconds",
  "/healthCheck/maxBlockAgeInSeconds",
  "/listenPort",
  "/nginx/clientBodyBufferSize",
  "/nginx/keepAliveRequests",
  "/nginx/keepAliveTimeout",
  "/nginx/proxyBuffering",
  "/nginx/proxyConnectTimeout",
  "/nginx/proxyProtocol",
  "/nginx/proxyRequestBuffering",
  "/ssl/bufferSize",
  "/ssl/certificate",
  "/ssl/certificateKey",
  "/ssl/ciphers",
  "/ssl/dhParam",
  "/ssl/protocols",
  "/ssl/sessionCacheSize",
  "/ssl/sessionTimeout",
  "/ssl/trustedCertificate",
]
check_cmd = "/usr/bin/openresty -t"
reload_cmd = "/usr/bin/openresty -s reload"
